spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8080}

application:
  security:
    api-key: ${API_KEY}

logging:
  level:
    com.assessment.position: INFO
    org.springframework: WARN
  file:
    name: /var/log/position-app.log

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false 